import { Geist, Geist_Mono } from "next/font/google";
import ResponsiveNavbar from "@/components/ResponsiveNavbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bevan Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scrollbar-hide scroll-smooth"> 
     <body
        className="min-h-dvh w-full relative text-white antialiased overflow-x-hidden scrollbar-hide"
        style={{
          background:
            "radial-gradient(125% 125% at 50% 10%, #000000 40%, #010133 100%)",
          backgroundAttachment: "fixed",
        }}
      >
        <ResponsiveNavbar/>
        {children}
      </body>
    </html>
  );
}
